#!/bin/bash

# Variables à personnaliser en fonction de votre environnement
CLUSTER_NAME="nom-de-votre-cluster"
CLUSTER_ENDPOINT="https://adresse-du-cluster"
USER_NAME="votre-nom-d-utilisateur"
USER_PASSWORD="votre-mot-de-passe"

# Obtenir le token d'authentification
TOKEN=$(kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep ${USER_NAME} | awk '{print $1}') | grep token: | awk '{print $2}')

# Configurer l'authentification du client avec le cluster
kubectl config set-cluster ${CLUSTER_NAME} --server=${CLUSTER_ENDPOINT}
kubectl config set-credentials ${USER_NAME} --token=${TOKEN}
kubectl config set-context ${CLUSTER_NAME} --cluster=${CLUSTER_NAME} --user=${USER_NAME}
kubectl config use-context ${CLUSTER_NAME}
