#!/bin/bash

# Variables d'authentification
CLUSTER_ENDPOINT="https://toto.group:8080"
USERNAME="votre_id"
PASSWORD="votre_mot_de_passe"
NAMESPACE="ilyes-test"

# Se connecter et récupérer le token d'authentification
TOKEN=$(curl -s -k -H "Content-Type: application/json" -X POST --data '{"username":"'$USERNAME'","password":"'$PASSWORD'"}' $CLUSTER_ENDPOINT/authenticate | jq -r '.token')

# Configurer kubectl pour utiliser le token d'authentification
kubectl config set-credentials $USERNAME --token=$TOKEN
kubectl config set-context $USERNAME --user=$USERNAME --cluster=$CLUSTER_ENDPOINT --namespace=$NAMESPACE
kubectl config use-context $USERNAME
