---
- name: Exécution du job Jenkins
  hosts: localhost  # Vous pouvez spécifier le nom de l'hôte où Ansible sera exécuté
  tasks:
    - name: Exécution du travail Jenkins
      uri:
        url: "https://jenkins-ilyes.group/p-3030-ilyes/test_ilyes/master/build"  # URL du travail Jenkins
        method: POST  # Méthode HTTP pour déclencher le travail (assurez-vous que POST est correct)
        status_code: 201  # Code de statut HTTP attendu pour une exécution réussie
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body: "token=VOTRE_TOKEN_JENKINS"  # Remplacez VOTRE_TOKEN_JENKINS par le token d'authentification Jenkins

      register: response

    - name: Vérification du résultat
      debug:
        var: response.status_code
